using LeaveManagement.Web.Constants;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LeaveManagement.Web.Configurations.Entities;

public class RoleSeedConfiguration : IEntityTypeConfiguration<IdentityRole>
{
    public void Configure(EntityTypeBuilder<IdentityRole> builder)
    {
        builder.HasData(
            new IdentityRole
            {
                // generated by hand, not linked to anything, just has value so that other seeding can always use same value
                Id = "11cbc596-3709-49b8-ad03-b53afd2e9a0f",
                Name = Roles.Administrator,
                NormalizedName = Roles.Administrator.ToUpper(),
            },
            new IdentityRole
            {
                // generated by hand, not linked to anything, just has value so that other seeding can always use same value
                Id = "d979dde0-1f98-4e30-a010-524d41d6b16d",
                Name = Roles.User,
                NormalizedName = Roles.User.ToUpper(),
            }
        );
    }
}